[pytest]
addopts = -v --tb=short --strict-markers --junitxml=reports/junit.xml --cov=app --cov-report=term-missing --cov-report=xml:reports/coverage.xml --cov-report=html:reports/htmlcov
testpaths = tests
python_files = test_*.py
